### PR TITLE
Update wallaby.js

### PR DESCRIPTION
**Pull request by ArtemGovorov**

### CODE REVIEW

**Comment by tomitrescak** [comment]
Artem, you are a magician! Works like a charm!!! Thanks.

One more detail .. is there any way to omit Typescript compilation at all since babel can now do typescript? I tried this but did not work:

```js
module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  process.env.NODE_ENV = 'test';

  var path = require('path');
  process.env.NODE_PATH +=
    path.delimiter +
    wallaby.projectCacheDir +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules');

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      `!${testPathExp}`
    ],

    tests: [testPathExp],

    env: {
      type: 'node',
      runner: 'node'
    },

    // compilers: {
    //   '**/*.ts?(x)': wallaby.compilers.typeScript({
    //     module: 'es6',
    //     jsx: 'jsx'
    //   })
    // },

    preprocessors: {
      '**/*.ts?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: ['react-app'],
          plugins: ['module:jsx-control-statements']
        })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts/' + p),
        '.',
        ['src']
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(ts|tsx|js|jsx)') && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

**Comment by tomitrescak** [comment]
I go so far as removing the preprocessor and adding this compiler:

```
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.babel({
        sourceMap: true,
        compact: false,
        presets: ['@babel/react', '@babel/typescript'],
        plugins: ['module:jsx-control-statements']
      })
    },
```

but does not work ;( It would be great to have a working example as when babel will launch v7 with typescript many people will start top use this.

**Comment by tomitrescak** [comment]
OK. It DID work! Here is a full config:

```js
module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  process.env.NODE_ENV = 'test';

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      `!${testPathExp}`
    ],

    tests: [testPathExp],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.babel({
        sourceMap: true,
        compact: false,
        presets: ['@babel/react', '@babel/typescript'],
        plugins: ['module:jsx-control-statements']
      })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts/' + p),
        '.',
        ['src']
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(ts|tsx|js|jsx)') && void delete jestConfig.transform[k]
      );
      console.log(jestConfig);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

**Comment by tomitrescak** [comment]
Argh, still no luck ;( it seems that class properties do not work with that and I do not know why ;(

```
class A {
  a = 2; // error
 
  a() { } // ok
}

**Comment by ArtemGovorov** [comment]
Looks like `@babel/typescript` doesn't support them (doesn't transform them at all).
I have [found this sample](https://github.com/DanielRosenwasser/babel-typescript-sample) and it looks like the `@babel/plugin-proposal-class-properties` is required in addition.

So 

```
yarn add @babel/plugin-proposal-class-properties
```

plus the following config should work for you (works for me on your repo)

```js
module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  process.env.NODE_ENV = 'test';

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      `!${testPathExp}`,
      '!src/**/*.d.ts'
    ],

    tests: [testPathExp],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.babel({
        babel: require('@babel/core'),
        presets: ['@babel/react', '@babel/typescript'],
        plugins: ['module:jsx-control-statements',  '@babel/proposal-class-properties']
      })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts/' + p),
        '.',
        ['src']
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(ts|tsx|js|jsx)') && void delete jestConfig.transform[k]
      );
      console.log(jestConfig);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

**Comment by tomitrescak** [comment]
@ArtemGovorov you are a star!!! Thanks .. works like a charm.

**Comment by tomitrescak** [comment]
Hmm, actually I am getting 

```
[Error] ​​Failed to run compilers on src/client/config/mocks.ts, Error: [BABEL] /Users/tomi/Github/learning/babel-ts/src/client/config/mocks.ts: You gave us a visitor for the node type ClassPrivateProperty but it's not a valid type (While processing: "/Users/tomi/Github/learning/babel-ts/node_modules/@babel/plugin-proposal-class-properties/lib/index.js")​​
```

I cloned a fresh repo and update config as you sent it to me.

**Comment by ArtemGovorov** [comment]
I have just forked your repo, added my changes (just the config above + installed the babel plugin for class properties), and it's working for me: https://github.com/ArtemGovorov/babel-ts. Try cloning the repo, running `yarn` and running wallaby.

**Comment by QuantumInformation** [comment]
what is the official create-react-app-ts demo repo?

**Pull request merged**
